function h = figure_note(str, varargin)
%FIGURE_NOTE (ps-utils): make little note in the bottom-right of figure
%   H = FIGURE_NOTE(STR, VARARGIN)
%
%  MH - http://github.com/histed/tools-mh

hold on
ha = axes('Visible', 'off');
text(1, -0.07, str, ...
     'FontSize', 8, ...
     'HorizontalAlignment', 'right', ...
     'VerticalAlignment', 'top', ...
     'Units', 'normalized', ...
     varargin{:});
