function av = behavParamsAV
    av(1).mouse = 613;
    av(2).mouse = 614;
    av(3).mouse = 616;
    av(4).mouse = 625;
    av(5).mouse = 626;
    av(6).mouse = 660;
    av(7).mouse = 668;
    av(8).mouse = 670;
    av(9).mouse = 672;
    av(1).col_str = 'm';
    av(2).col_str = 'b';
    av(3).col_str = 'r';
    av(4).col_str = 'c';
    av(5).col_str = 'g';
    av(6).col_str = 'y';    
    av(7).col_str = 'k';  
    av(8).col_str = 'k';  
    av(9).col_str = 'k';
end