function cs = tempHADC8ConstantList

cs.constListHADC8 = ...  % all the saved variables
    { 'doExtendItiOnShortPrevTrial', ...
      'doLaserStim', ...
      'doLever', 'doLeverSolenoidAllTrials', ...
      'doLeverSolenoidOnEarly', 'doLeverSolenoidOnMiss', ...
      'doVisualStim', ...
      'doGeomHoldDist', ...
      'geomHoldMeanMs', ...
      'earlyTimeoutMs', 'experimentXmlTrialId', ...
      'fakeMouseMaxPressMs', 'fakeMouseMaxReactMs', ...
      'fixedReqHoldTimeMs', 'forceMinStimStepTo', ...
      'gratingAzimuthDeg', 'gratingContrastMax', ...
      'gratingContrastStepsPerOctave', 'gratingElevationDeg', ...
      'gratingHeightDeg', 'gratingSpatialFreqCPD', ...
      'gratingSpeedDPS', 'gratingWidthDeg', ...
      'gratingDirectionDeg', ...
      'gratingDurationMs', ...
      'interRewardIntervalMs', 'itiTimeMs', ...
      'itiExtraRandTimeMs', ...
      'laserDoLinearRamp', 'laserDoPulseTrain', ...
      'laserOffPowerMw', 'laserPeakMaxMw', ...
      'laserPeakStepsPerOctave', 'laserPulseLengthMs', ...
      'laserPulsePeriodMs', 'laserRampLengthMs', ...
      'laserTrainLengthMs', 'laserTransitionRampUpDownMs', ...
      'laserTransitionDoExpRamp', ...
      'laserRampExtraConstantLengthMs', ...
      'laserRampDoExpRamp', ...
      'laserBaselinePowerMw', ...
      'trialLaserPowerMw', ...
      'trialLaserOnTimeMs', ...
      'trialLaserOffTimeMs', ...
      'maxConsecCorrects', ...
      'nConsecErrorsCauseTimeout', ...
      'consecErrorTimeoutS', ...
      'doLongBonus', ...
      'longBonusExtraHoldTimeMs', ...
      'longBonusExtraRewardUs', ...
      'maxRewardUs', ...
      'minRewardUs', ...
      'missedTimeoutMs', ...
      'postRewardMs', ...  
      'randReqHoldMaxMs', ...
      'reactTimeMs', ...
      'subjectNum', ...
      'trPer80Level1', 'trPer80Level2', 'trPer80Level3', ...
      'trPer80Level4', 'trPer80Level5', 'trPer80Level6', ...
      'trPer80Level7', 'trPer80Level8', ...
      'doBlock2', 'doBlock2SeparateOdds', ...
      'block2TrPer80Level1', 'block2TrPer80Level2', 'block2TrPer80Level3', ...
      'block2TrPer80Level4', 'block2TrPer80Level5', 'block2TrPer80Level6', ...
      'block2TrPer80Level7', 'block2TrPer80Level8', ...
      'block2DoRampLength', 'block2RampLengthMs2', ...
      'block2RampLengthPowerMaxMw2', ...
      'block2DoRampVTrain', ...
      'block2RvtTrainPowerMaxMw', ...
      'block2RvtTrainStepsPerOctave', ...
      'block2RvtRampBaselinePowerMw', ...
      'block2RvtTrainBaselinePowerMw', ...
      'block2DoGratingAppearance', ...
      'block2GratingDirectionDeg', ...
      'block2GratingElevationDeg', ...
      'block2GratingAzimuthDeg', ...
      'block2GratingHeightDeg', ...
      'block2GratingWidthDeg', ...
      'block2GratingSpatialFreqCPD', ...
      'block2GratingSpeedDPS', ...
      'block2GratingDurationMs', ...
      'block2GratingContrastMax', ...
      'block2GratingContrastStepsPerOctave', ...
      'block2DoRampVTrain', 'block2RvtTrainPowerMaxMw', ...
      'block2DoTrialLaser', 'block2TrialLaserPowerMw', ...
      'block2TrialLaserOnTimeMs', ...
      'block2TrialLaserOffTimeMs', ...
      'block2TrialLaserContrastMax', 'block2TrialLaserContrastStepsPerOctave', ...
      'tooFastTimeMs' };

cs.constListDP =  ...  % all the saved variables
    { 'subjectNum' ...
      'preventDualReleaseTimeMs'...
      'leverSolenoidDoDuringIti' ...
      'leverSolenoidDoOnMiss' ...
      'leverSolenoidDoOnEarly'...
      'leverSolenoidDoBothSideIncorr'...
      'leverSolenoidDoStimSideIncorr'...
      'leverSolenoidDoAllTrials'...
      'leverSolenoidDoStageOne'...
      'timeoutEarlyMs'...
      'timeoutMissedMs'...
      'timeoutIncorrectMs'...
      'timeoutDualReleaseMs'...
      'rightReqHoldMs'...
      'leftReqHoldMs'...
      'reactTimeMs'...
      'reactTooFastMs'...
      'itiFixedTimeMs'...
      'itiRandTimeMs'...
      'rightRewardUs'...
      'leftRewardUs'...
      'rewardConsecNCorrectMax'...
      'rewardConsecGapTimeMs'...
      'rewardDoStaircase', ...
      'rewardStaircaseSumUs', ...
      'rewardStaircaseMinValUs', ...
      'rewardStaircaseNTrialsBeforeStart', ...
      'rewardStaircaseThisTrialWeight', ...
      'consecErrorNTrialsCauseTimeout'...
      'consecErrorTimeoutS'...
      'stimProbAvgLeft'...
      'stimProbAvgSwitch'...
      'trPer80Level1'...
      'trPer80Level2'...
      'trPer80Level3'...
      'trPer80Level4'...
      'trPer80Level5'...
      'trPer80Level6'...
      'trPer80Level7'...
      'trPer80Level8'...
      'rightGratingHeightDeg'...
      'rightGratingWidthDeg'...
      'rightGratingDirectionDeg'...
      'rightGratingElevationDeg'...
      'rightGratingAzimuthDeg'...
      'rightGratingSpatialFreqCPD'...
      'rightGratingSpeedDPS'...
      'rightGratingDurationMs'...
      'rightGratingContrast8StepsMax'...
      'rightGratingContrastSPO' ...
      'leftGratingHeightDeg'...
      'leftGratingWidthDeg'...
      'leftGratingDirectionDeg'...
      'leftGratingElevationDeg'...
      'leftGratingAzimuthDeg'...
      'leftGratingSpatialFreqCPD'...
      'leftGratingSpeedDPS'...
      'leftGratingDurationMs'...
      'leftGratingContrast8StepsMax'...
      'leftGratingContrastSPO'...
      'doBlock2'...
      'doRightLaserStim'...
      'rightLaserPowerMaxMw'...
      'rightLaserTrialContrastMax'...
      'rightLaserTrialContrastSPO'...
      'doLeftLaserStim'...
      'leftLaserPowerMaxMw' ...
      'leftLaserTrialContrastMax'...
      'leftLaserTrialContrastSPO'...
      'fakeMouseOn'...
      'fakeMouseMaxPressMs' ...
      'fakeMouseMaxReactMs' };
