function [retval] = HoldAndDetectConstant(data_struct, input)
% Main matlab online function for HADC8
%
%  MH 100115: created
%  MH 130107: refactored into new expt* functions.
% call: exptSetupBridge, exptProcessBridgeInput, do your own thing, then exptRunSubfunctions

if nargin < 2,
    input = [];
end

ds = data_struct;
addpath('~/Repositories/BehaviorCode-Glickfeld-Hull/BehaviorCode/NewSkeletonCode/MatlabSharedCode');
addpath('~/Repositories/BehaviorCode-Glickfeld-Hull/BehaviorAnalysis');

oneValEachTrialNames = {...
    'tTrialStartMWTimestampMs', ...
    'tItiWaitTimeMs', ...
    'tThisTrialStartTimeMs', ...
    'tLastTrialStartTimeMs', ...
    'tTempStim1', ...
    'tTempStim2', ...
    'tTempDist1', ...
    'tTempDist2', ...
    'tStimulusNumber', ...
    'tStimulusNumber2', ...
    'tDistNumber', ...
    'tDistNumber2', ...
    'tStimOneGratingOnTimeMs', ...
    'tStimTwoGratingOnTimeMs', ...
    'tISITimeMs', ...
    'tStimOneDoVisualStim', ...
    'tTargetOneGratingContrast', ...
    'tTargetOneGratingDirectionDeg', ...
    'tTargetOneGratingElevationDeg', ...
    'tTargetOneGratingAzimuthDeg', ...
    'tTargetOneGratingDiameterDeg', ...
    'tTargetOneGratingSpatialFreqCPD', ...
    'tTargetOneGratingTemporalFreqCPS', ...
    'tTargetOneGratingPhaseDeg', ...
    'tDistractOneGratingContrast', ...
    'tDistractOneGratingDirectionDeg', ...
    'tDistractOneGratingPhaseDeg', ...
    'tDistractOneGratingTemporalFreqCPS', ...
    'tDistractOneGratingSpatialFreqCPD', ...
    'tDistractOneGratingAzimuthDeg', ...
    'tDistractOneGratingElevationDeg', ...
    'tDistractOneGratingDiameterDeg', ...
    'tStimTwoDoVisualStim', ...
    'tTargetTwoGratingContrast', ...
    'tTargetTwoGratingDirectionDeg', ...
    'tTargetTwoGratingElevationDeg', ...
    'tTargetTwoGratingAzimuthDeg', ...
    'tTargetTwoGratingDiameterDeg', ...
    'tTargetTwoGratingSpatialFreqCPD', ...
    'tTargetTwoGratingTemporalFreqCPS', ...
    'tTargetTwoGratingPhaseDeg', ...
    'tDistractTwoGratingContrast', ...
    'tDistractTwoGratingDirectionDeg', ...
    'tDistractTwoGratingPhaseDeg', ...
    'tDistractTwoGratingTemporalFreqCPS', ...
    'tDistractTwoGratingSpatialFreqCPD', ...
    'tDistractTwoGratingAzimuthDeg', ...
    'tDistractTwoGratingElevationDeg', ...
    'tDistractTwoGratingDiameterDeg', ...
    'tDoMatrix', ...
    'tDoRandISITime', ...
    'tDoRandStimOnTime', ...
    'tDoRandCon', ...
    'tDoRandDir', ...
    'tDoDistRandDir', ...
    'tDoRandPos', ...
    'tDoRandSF', ...
    'tDoRandTF', ...
    'tDoRandPhase', ...
    'tDoRandDiameter',...
    'tNStimAccepted', ...
    'tItiWaitFrames', ...
    'nStimOneFramesOn', ...
    'nStimTwoFramesOn', ...
    'nFramesISI', ...
    'cItiStart',...
    'cStimOneOn',...
    'cStimTwoOn',...
    'cStimOneOff',...
    'cStimTwoOff',...
    'mwStimOneOnMs',...
    'mwStimTwoOnMs',...
    'mwStimOneOffMs',...
    'mwStimTwoOffMs',...
};

events = ds.events;
eventsTrial = events;

if isempty(input),
    input.trialSinceReset = 1;
    input.startDateVec = datevec(now);
    input.saveTime = datestr(now, 'yymmdd-HHMM');
    input.savedEvents = {};
    input.eventCodecs = {};
    input.eventCodecs{1} = ds.event_codec;
    nOne = length(oneValEachTrialNames);
    for iV = 1:nOne
        input.(oneValEachTrialNames{iV}) = {};
    end
else
    input.trialSinceReset = input.trialSinceReset+1;
end
trN = input.trialSinceReset;

% Consts that govern tValues
input.constList = { 'subjectNum',...
    'speedIntervalMS', ...
    'doMatrix', ...
    'doRandISITime', ...
    'doRandStimOnTime', ...
    'doRandCon', ...
    'doZeroCon',...
    'zeroConPer80',...
    'doRandDir', ...
    'doDistractRandDir', ...
    'doRandPos', ...
    'doRandDiameter', ...
    'doRandSF', ...
    'doRandTF', ...
    'doRandPhase', ...
    'doWheelSpeed', ...
    'frameRateHz', ...
    'itiTimeMs', ...
    'stimOneDoVisualStim', ...
    'stimOneGratingOnTimeMs', ...
    'targetOneGratingContrast', ...
    'targetOneGratingDirectionDeg', ...
    'targetOneGratingElevationDeg', ...
    'targetOneGratingAzimuthDeg', ...
    'targetOneGratingDiameterDeg', ...
    'targetOneGratingSpatialFreqCPD', ...
    'targetOneGratingTemporalFreqCPS', ...
    'targetOneGratingPhaseDeg', ...
    'distractOneGratingContrast', ...
    'distractOneGratingDirectionDeg', ...
    'distractOneGratingPhaseDeg', ...
    'distractOneGratingTemporalFreqCPS', ...
    'distractOneGratingSpatialFreqCPD', ...
    'distractOneGratingAzimuthDeg', ...
    'distractOneGratingElevationDeg', ...
    'distractOneGratingDiameterDeg', ...
    'stimTwoDoVisualStim', ...
    'stimTwoGratingOnTimeMs', ...
    'targetTwoGratingContrast', ...
    'targetTwoGratingDirectionDeg', ...
    'targetTwoGratingElevationDeg', ...
    'targetTwoGratingAzimuthDeg', ...
    'targetTwoGratingDiameterDeg', ...
    'targetTwoGratingSpatialFreqCPD', ...
    'targetTwoGratingTemporalFreqCPS', ...
    'targetTwoGratingPhaseDeg', ...
    'distractTwoGratingContrast', ...
    'distractTwoGratingDirectionDeg', ...
    'distractTwoGratingPhaseDeg', ...
    'distractTwoGratingTemporalFreqCPS', ...
    'distractTwoGratingSpatialFreqCPD', ...
    'distractTwoGratingAzimuthDeg', ...
    'distractTwoGratingElevationDeg', ...
    'distractTwoGratingDiameterDeg', ...
    'matchTargetOneParameters',...
    'matchDistractOneParameters',...
};

for iV = 1:length(oneValEachTrialNames)
    tName = oneValEachTrialNames{iV};
    input.(tName){trN} = mwGetEventValue(eventsTrial, ds.event_codec, tName, 'last', 1);
end

nSync = length(mwGetEventValue(ds.events, ds.event_codec, ...
                             'sync', 'all', 'ignoreMissing'));

                         
syncCode = codec_tag2code(ds.event_codec, 'sync');
codeList = [ds.events.event_code];
syncNs = find(codeList == syncCode);                        
if nSync >= 4,
  % if 6 codes, pull out consts from first block and leave last
  % (Somewhat dangerous)
  constsStruct = struct;
  constsStruct = ds.events(1:syncNs(3));
  trialStruct = ds.events(syncNs(end-1):end);
  ds.events = trialStruct;
end


nConsts = length(input.constList);
for iC = 1:nConsts
  tCN = input.constList{iC};
  if input.trialSinceReset==1  % use dump on first trial
    tCV1 = mwGetEventValue(constsStruct, ds.event_codec, tCN, [], ...
                          'ignoremissing');
    input.(tCN) = tCV1;
  
  else  % look for changes on all trials
    tCV = mwGetEventValue(ds.events, ds.event_codec, tCN, [], ...
                          'ignoremissing');
    if ~isempty(tCV)
      input.(tCN) = tCV;
    end
  end
end
 
% Look for changes in constants for all trials
b={};
for iC = 1:nConsts
  tCN = input.constList{iC};
  tV = mwGetEventValue(ds.events, ds.event_codec, tCN, [], 'ignoremissing');
 
  if ~isempty(tV), 
    % Constructs array of changed consts and when they changed
    b(end+1,1:2) = {tCN, tV};
  end
end
input.constChangedOnTrial{input.trialSinceReset} = b;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

trN = input.trialSinceReset;

%% Counter/Frames Synchronization Section
try
    input.counterTimesUs{trN} = mwGetEventTime(eventsTrial, ds.event_codec, 'counter', 'all', [], 1);
    input.counterValues{trN} = mwGetEventValue(eventsTrial, ds.event_codec, 'counter', 'all', 1) ;
catch
    input.counterTimesUs{trN} = NaN;
    input.counterValues{trN} = NaN;
end

try
    input.wheelSpeedTimesUs{trN} = mwGetEventTime(ds.events, ds.event_codec, 'wheelSpeed', 'all', [], 1);
    input.wheelSpeedValues{trN} = mwGetEventValue(ds.events, ds.event_codec, 'wheelSpeed', 'all', 1) ;
catch
    input.wheelSpeedTimesUs{trN} = NaN;
    input.wheelSpeedValues{trN} = NaN;
end

%% disp status

trStr = ['Trial ' num2str(trN) '- '];
if input.tTargetOneGratingContrast{trN} > 0
    target1Str = sprintf('Target1: con %g%%, dir %g%, %g% ms', input.tTargetOneGratingContrast{trN}.*100, input.tTargetOneGratingDirectionDeg{trN}, input.tStimTwoGratingOnTimeMs{trN});
else
    target1Str = sprintf('Target1: none');
end
if input.tDistractOneGratingContrast{trN} > 0
    distract1Str = sprintf('Distract1: con %g%%, dir %g%, %g% ms', input.tDistractOneGratingContrast{trN}*100, input.tDistractOneGratingDirectionDeg{trN}, input.tStimTwoGratingOnTimeMs{trN});
else
    distract1Str = sprintf('Distract1: none');
end
if input.tTargetTwoGratingContrast{trN} > 0
    target2Str = sprintf('Target2: con %g%%, dir %g%, %g% ms', input.tTargetTwoGratingContrast{trN}.*100, input.tTargetTwoGratingDirectionDeg{trN}, input.tStimTwoGratingOnTimeMs{trN});
else
    target2Str = sprintf('Target2: none');
end
if input.tDistractTwoGratingContrast{trN} > 0
    distract2Str = sprintf('Distract2: con %g%%, dir %g%, %g% ms', input.tDistractTwoGratingContrast{trN}*100, input.tDistractTwoGratingDirectionDeg{trN}, input.tStimTwoGratingOnTimeMs{trN});
else
    distract2Str = sprintf('Distract2: none');
end
isiStr = sprintf('ISI: %g%ms', input.tISITimeMs{trN});

itiStr = sprintf('iti %d, ', round(input.tItiWaitTimeMs{trN}));
fprintf(1,'%s %s; %s; %s; %s \n', ...
    trStr, target1Str, target2Str, distract1Str, distract2Str, isiStr);

%% run subfunctions
input = exptRunSubfunctions(ds, input, { @plotPairStim_2P_Frames });


input.savedDataName = sprintf('%s/data-i%03s-%s.mat', ...
                              '~/Documents/MWorks/Data', ...
                              mat2str(input.subjectNum), input.saveTime);
save(input.savedDataName, 'input');

%% save variables for next trial
retval = input;

return


